from scapy.all import conf

conf.use_pcap = True

EXIT_SUCCESS = 0
EXIT_FAILURE = 1

MAX_VERBOSITY = 3
MEDIUM_VERBOSITY = 2
MINIMUM_VERBOSITY = 1
DEFAULT_VERBOSITY = 0
VERBOSITY_LEVELS = (
    DEFAULT_VERBOSITY,
    MINIMUM_VERBOSITY,
    MEDIUM_VERBOSITY,
    MAX_VERBOSITY,
)
LOG_DIR = "/var/log/port-scanner/"


HTTP_PORTS = {80, 8080}
HTTPS_PORTS = {443, 8443}
ALL_HTTP_PORTS = HTTP_PORTS.union(HTTPS_PORTS)
SSH_PORT = 22
SYN_ACK_FLAG = 0x12
RESET_FLAG = 0x04
ICMP_UNREACHABLE_TYPE = 3

DEFAULT_TIMEOUT = 1.5
DEFAULT_READ_BYTES = 1024
DEFAULT_CONCURRENCY_FOR_SCANS = 450
DEFAULT_CONCURRENCY_FOR_BANNER_GRAB = 50
DEFAULT_RETRY_COUNT = 0

SCANNER_CLASSES = {}
TCP_SCAN = "tcp"
SYN_SCAN = "syn"
SCAN_CHOICES = (TCP_SCAN, SYN_SCAN)


DEFAULT_PORT_RANGE = range(1, 1026)
DEFAULT_PORT_SCAN_TYPE = TCP_SCAN
DEFAULT_VERBOSE_LEVEL = DEFAULT_VERBOSITY

TEXT_FORMAT = "txt"
JSON_FORMAT = "json"
CSV_FORMAT = "csv"
FORMAT_TYPES = (TEXT_FORMAT, JSON_FORMAT, CSV_FORMAT)
OUTPUT_TO_FILE = True
OUTPUT_TO_CONSOLE = False
DEFAULT_OUTPUT_MEDIUM = (TEXT_FORMAT, OUTPUT_TO_CONSOLE)

DEFAULT_USER_AGENT = "Mozilla/1.0"
DEFAULT_SERVICE_BANNER_GRAB = False

PORT_NOT_ALLOWED = 0
MINIMUM_PORT = 1
MAXIMUM_PORT = 65535

THRESHOLD_FOR_SLOW_SCAN = 20000
SYN_SCAN_BATCH_SIZE = 2000

OPEN_PORT = "OPEN"
CLOSED_PORT = "CLOSED"
FILTERED_PORT = "FILTERED"

NO_ROUTE_TO_HOST_ERRNO = 113
NETWORK_UNREACHABLE_ERRNO = 101
ETIMEDOUT_ERRNO = 110

ERRORNO_LIST = [
    NO_ROUTE_TO_HOST_ERRNO,
    NETWORK_UNREACHABLE_ERRNO,
    ETIMEDOUT_ERRNO,
]
