from utils.logger import logger
from scapy.all import conf

conf.use_pcap = True

MAX_VERBOSITY = 3
MEDIUM_VERBOSITY = 2
MINIMUM_VERBOSITY = 1
DEFAULT_VERBOSITY = 0

HTTP_PORTS = {80, 8080}
HTTPS_PORTS = {443, 8443}
ALL_HTTP_PORTS = HTTP_PORTS.union(HTTPS_PORTS)
SSH_PORT = 22

DEFAULT_TIMEOUT = 1.5
DEFAULT_READ_BYTES = 1024
DEFAULT_CONCURRENCY_FOR_SCANS = 450
DEFAULT_CONCURRENCY_FOR_BANNER_GRAB = 50
DEFAULT_RETRY_COUNT = 0

DEFAULT_PORT_RANGE = range(1, 1026)
DEFAULT_PORT_SCAN_TYPE = "tcp"
DEFAULT_VERBOSE_LEVEL = DEFAULT_VERBOSITY
DEFAULT_OUTPUT_MEDIUM = ("txt", False)
DEFAULT_USER_AGENT = "Mozilla/1.0"
DEFAULT_SERVICE_BANNER_GRAB = False

VERBOSITY_LEVELS = (DEFAULT_VERBOSITY, MINIMUM_VERBOSITY, MEDIUM_VERBOSITY, MAX_VERBOSITY)
SCAN_CHOICES = ("tcp", "synscan")

PORT_NOT_ALLOWED = 0
MINIMUM_PORT = 1
MAXIMUM_PORT = 65535

THRESHOLD_FOR_SLOW_SCAN = 20000
SYN_SCAN_BATCH_SIZE = 2000

NO_ROUTE_TO_HOST_ERRNO = 113
NETWORK_UNREACHABLE_ERRNO = 101
ETIMEDOUT_ERRNO = 110

ERRORNO_LIST = [
    NO_ROUTE_TO_HOST_ERRNO,
    NETWORK_UNREACHABLE_ERRNO,
    ETIMEDOUT_ERRNO,
]

OPEN_PORT = "OPEN"
CLOSED_PORT = "CLOSED"
FILTERED_PORT = "FILTERED"

OUTPUT_TO_FILE = True
OUTPUT_TO_CONSOLE = False
INVALID_OUTPUT_FORMAT_ERROR_MSG = "Invalid output format specified."

INVALID_CIDR_ERROR_MSG = "Invalid CIDR notation specified."
INVALID_IP_ERROR_MSG = "Invalid IP address specified."
INVALID_IP_RANGE_ERROR_MSG = "Invalid IP range specified."

INVALID_IP_EXCLUSION_ERROR_MSG = "Invalid IP exclusion specified."
INVALID_PORT_EXCLUSION_ERROR_MSG = "Invalid port exclusion specified."

INVALID_PORT_RANGE_ERROR_MSG = f"Invalid port or port range specified. Please provide ports between {MINIMUM_PORT} and {MAXIMUM_PORT}."
INVALID_PORT_MSG = f"Port must be between {MINIMUM_PORT} and {MAXIMUM_PORT}."
