from utils.logger import logger
from scapy.all import conf

conf.use_pcap = True

MAX_VERBOSITY = 3
MEDIUM_VERBOSITY = 2
MINIMUM_VERBOSITY = 1
DEFAULT_VERBOSITY = 0

HTTP_PORTS = {80, 8080}
HTTPS_PORTS = {443, 8443}
ALL_HTTP_PORTS = HTTP_PORTS.union(HTTPS_PORTS)
SSH_PORT = 22

DEFAULT_TIMEOUT = 1.5
DEFAULT_READ_BYTES = 1024
DEFAULT_CONCURRENCY_FOR_SCANS = 450
DEFAULT_CONCURRENCY_FOR_BANNER_GRAB = 50
DEFAULT_RETRY_COUNT = 0

DEFAULT_PORT_RANGE = range(1, 1026)
DEFAULT_PORT_SCAN_TYPE = "tcp"
DEFAULT_VERBOSE_LEVEL = DEFAULT_VERBOSITY
DEFAULT_OUTPUT_MEDIUM = ("plain text", False)
DEFAULT_NO_RESOLVE = False
DEFAULT_USER_AGENT = "Mozilla/1.0"
DEFAULT_BANNER_GRAB = False

VERBOSITY_LEVELS = (DEFAULT_VERBOSITY, MINIMUM_VERBOSITY, MEDIUM_VERBOSITY, MAX_VERBOSITY)
SCAN_CHOICES = ("tcp", "synscan")

THRESHOLD_FOR_SLOW_SCAN = 20000
SYN_SCAN_BATCH_SIZE = 2000

NO_ROUTE_TO_HOST_ERRNO = 113
NETWORK_UNREACHABLE_ERRNO = 101
ETIMEDOUT_ERRNO = 110

ERRORNO_LIST = [
    NO_ROUTE_TO_HOST_ERRNO,
    NETWORK_UNREACHABLE_ERRNO,
    ETIMEDOUT_ERRNO,
]
